from __future__ import annotations


PROVIDERS = {
    "UN Comtrade": {
        "provider": "UN Comtrade",
        "category": "market_data",
        "cost_model": "public_free",
        "api_backed": True,
        "zero_cost_core": True,
        "allowed_use": "Public trade data for target-market selection.",
        "notes": "Use for HS 7019 country prioritization before lead discovery.",
    },
    "Manual CSV": {
        "provider": "Manual CSV",
        "category": "manual_import",
        "cost_model": "public_free",
        "api_backed": False,
        "zero_cost_core": True,
        "allowed_use": "Manual spreadsheet import from user-controlled files.",
        "notes": "Core workflow must work with manual CSV alone.",
    },
    "外贸邦": {
        "provider": "外贸邦",
        "category": "bill_of_lading",
        "cost_model": "manual_or_platform_plan",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "Manual import of platform-exported or user-copied public bill-of-lading clues.",
        "notes": "Do not scrape logged-in pages unless the account terms explicitly allow it.",
    },
    "易之家": {
        "provider": "易之家",
        "category": "bill_of_lading",
        "cost_model": "manual_or_platform_plan",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "Manual import of platform-exported or user-copied public bill-of-lading clues.",
        "notes": "Do not scrape logged-in pages unless the account terms explicitly allow it.",
    },
    "Serper": {
        "provider": "Serper",
        "category": "search",
        "cost_model": "free_credit_or_paid",
        "api_backed": True,
        "zero_cost_core": False,
        "allowed_use": "Google SERP API for public web search discovery.",
        "notes": "Has free trial queries; continued use requires paid credits.",
    },
    "Apollo.io": {
        "provider": "Apollo.io",
        "category": "contact_enrichment",
        "cost_model": "free_credit_or_paid",
        "api_backed": True,
        "zero_cost_core": False,
        "allowed_use": "Official API or exported CSV for internal contact enrichment.",
        "notes": "Do not scrape the logged-in SaaS dashboard.",
    },
    "Hunter.io": {
        "provider": "Hunter.io",
        "category": "contact_enrichment",
        "cost_model": "free_credit_or_paid",
        "api_backed": True,
        "zero_cost_core": False,
        "allowed_use": "Official API or exported CSV for domain email search and verification.",
        "notes": "Do not scrape the logged-in SaaS dashboard.",
    },
    "Snov.io": {
        "provider": "Snov.io",
        "category": "contact_enrichment",
        "cost_model": "free_credit_or_paid",
        "api_backed": True,
        "zero_cost_core": False,
        "allowed_use": "Official API or exported CSV for email finding and verification.",
        "notes": "Do not scrape the logged-in SaaS dashboard.",
    },
    "Bright Data": {
        "provider": "Bright Data",
        "category": "public_web_collection",
        "cost_model": "paid",
        "api_backed": True,
        "zero_cost_core": False,
        "allowed_use": "Paid collection for public web pages only.",
        "notes": "Do not use for logged-in pages, paywalled data, or bypassing account restrictions.",
    },
    "Panjiva": {
        "provider": "Panjiva",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "ImportGenius": {
        "provider": "ImportGenius",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "ZoomInfo": {
        "provider": "ZoomInfo",
        "category": "contact_database",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "Lusha": {
        "provider": "Lusha",
        "category": "contact_enrichment",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "BuiltWith": {
        "provider": "BuiltWith",
        "category": "website_intelligence",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "SimilarWeb": {
        "provider": "SimilarWeb",
        "category": "traffic_intelligence",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "跨境搜": {
        "provider": "跨境搜",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "跨境魔方": {
        "provider": "跨境魔方",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "Tendata": {
        "provider": "Tendata",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "TradeInfo": {
        "provider": "TradeInfo",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "孚盟软件": {
        "provider": "孚盟软件",
        "category": "crm_intelligence",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "信风数据": {
        "provider": "信风数据",
        "category": "contact_enrichment",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
    "格兰德": {
        "provider": "格兰德",
        "category": "trade_data",
        "cost_model": "paid_or_contract",
        "api_backed": False,
        "zero_cost_core": False,
        "allowed_use": "CSV import from user-authorized trade data exports.",
        "notes": "Do not scrape logged-in or paid member pages.",
    },
}


ALIASES = {
    "serper.dev": "Serper",
    "serper": "Serper",
    "apollo": "Apollo.io",
    "apollo.io": "Apollo.io",
    "hunter": "Hunter.io",
    "hunter.io": "Hunter.io",
    "snov": "Snov.io",
    "snov.io": "Snov.io",
    "brightdata": "Bright Data",
    "bright data": "Bright Data",
    "panjiva": "Panjiva",
    "importgenius": "ImportGenius",
    "zoominfo": "ZoomInfo",
    "lusha": "Lusha",
    "builtwith": "BuiltWith",
    "similarweb": "SimilarWeb",
    "tendata": "Tendata",
    "tradeinfo": "TradeInfo",
    "comtrade": "UN Comtrade",
    "un comtrade": "UN Comtrade",
    "waitubang": "外贸邦",
    "yizhijia": "易之家",
}


def provider_summary(name: str) -> dict:
    key = ALIASES.get(str(name or "").strip().lower(), str(name or "").strip())
    return dict(PROVIDERS.get(key, PROVIDERS["Manual CSV"]))


def provider_report() -> dict:
    providers = sorted(PROVIDERS.values(), key=lambda item: (not item["zero_cost_core"], item["provider"]))
    return {"providers": [dict(item) for item in providers]}
